// <auto-generated />
using System;
using BeniaLite.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeniaLite.Api.Migrations
{
    [DbContext(typeof(BeniaDbContext))]
    [Migration("20260119140740_AddSymptomLogs")]
    partial class AddSymptomLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeniaLite.Api.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SymptomLogId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SymptomLogId");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.RoutineCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RoutineId", "CompletedAtUtc");

                    b.ToTable("RoutineCompletions");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.RoutineStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FrequencyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FrequencyValue")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId", "SortOrder")
                        .IsUnique();

                    b.ToTable("RoutineSteps");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.SymptomLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Severity0to10")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LoggedAtUtc");

                    b.ToTable("SymptomLogs");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.SymptomLogTrigger", b =>
                {
                    b.Property<Guid>("SymptomLogId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TriggerTagId")
                        .HasColumnType("uuid");

                    b.HasKey("SymptomLogId", "TriggerTagId");

                    b.HasIndex("TriggerTagId");

                    b.ToTable("SymptomLogsTrigger");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.TriggerTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("TriggerTags");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.Photo", b =>
                {
                    b.HasOne("BeniaLite.Api.Entities.SymptomLog", "SymptomLog")
                        .WithMany("Photos")
                        .HasForeignKey("SymptomLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SymptomLog");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.RoutineStep", b =>
                {
                    b.HasOne("BeniaLite.Api.Entities.Routine", "Routine")
                        .WithMany("Steps")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.SymptomLogTrigger", b =>
                {
                    b.HasOne("BeniaLite.Api.Entities.SymptomLog", "SymptomLog")
                        .WithMany("Triggers")
                        .HasForeignKey("SymptomLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeniaLite.Api.Entities.TriggerTag", "TriggerTag")
                        .WithMany("SymptomLogs")
                        .HasForeignKey("TriggerTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SymptomLog");

                    b.Navigation("TriggerTag");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.Routine", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.SymptomLog", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("BeniaLite.Api.Entities.TriggerTag", b =>
                {
                    b.Navigation("SymptomLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
